Reproducible-Bioinformatics/CAR-NGS

R/dimensions.R, R/utils/docker.R
- **feat: add run_in_docker function**
- **feat: add is_running_in_docker function**
- **feat: rewrite dimensions**
- **fix: rename function variables to something more descriptive**
- **fix: change volume mount from vector to list**
- **feat: add path normalization logic**
- **feat: add with_scratch_directory function**
- **feat: add modifier to with_scratch_directory**
- **chore: move run_in_docker and is_running_in_docker & add documentation**
- **fix: change function form**
=> feat: restructure dimensions function 

.Rbuildignore, .gitignore, DESCRIPTION, Makefile, NAMESPACE
- **fix: update DESCRIPTION to match current R specifications**
- **feat: declare imports in DESCRIPTION.**
- **feat: add license template file**
- **feat: add ignore files**
- **feat: add makefile**
- **fix: remove namespace**
=> feat: add makefile and according documentation

R/cellrangerIndexing.R
Changes to the function form and upgrade of the documentation accordingly
=> fix: change function form

R/atacSeq.R
Adding the function with the proper documentation after testing it
=> feat(Atac-seq): add atacSeq function

R/heatmap.R
Adding heatmap function and related documentation
=> feat(heatmap): add heatmap function

R/cdsa.R
CompleteDownStreamAnalysis pipeline function for bulk RNA-seq
=> feat (cdsa): add cdsa function

R/index_align.R
Function for indexing and alignment of bulk RNA-seq
=> feat (index_align): add index_align function

R/pca.R
Adding pca function and related documentation
=> feat(pca): add pca function

R/deseq2.R
Adding deseq2 function and related documentation
=> feat(deseq2): add deseq2 function

R/cellrangerIndexing.R
nThreads type has been changed from integer to double
=> fix (cellrangerIndexing): change of nThreads type

R/detectSeq.R
Adding detectSeq function and related documentation
=> feat (detectSeq): add detectSeq function

R/mitoRibo.R
Adding mitoRibo.R function, which is the updated version of mitoriboUmi, following the new singlecell analysis pipeline. This function is yet to be tested (I am currently having wifi issues), so it may present bugs that will need to be fixed later.
=> feat(mitoRibo): add mitoRibo function

R/singlecell_alignIndex.R
Adding singlecell_alignIndex.R function. This function has yet to be tested, so there may be the need to fix additional bugs.
=> feat(singlecell_alignIndex): add singlecell_alignIndex function

R/singlecell_featureSelection.R
Adding singlecell_featureSelection.R function. This function is yet to be tested, so may present bugs that will need to be fixed.
=> feat(singlecell_featureSelection): add featureSelection function

R/singlecell_clustering.R
Adding singlecell_clustering.R function, that has yet to be tested (bug fixes may be needed in future).
=> feat(singlecell_clustering): add singlecell_clustering function

R/mitoRibo.R
I accidentaly typed a "." instead of a ","...
=> fix: spellling mistake

R/singlecell_alignIndex.R
the .sh function inside the docker requires the input to be in a character form over a logical
=> fix: variable type changed from logical to character

R/singlecell_featureSelection.R
Improving the intrface with the docker container so that no errors arise.
=> fix: remove bugs

R/modules.R
The function is still missing a documentation and needs some bugs fixed.
=> feat(modules): add modules R function

R/modules.R
Changed the docker to one with the correct permissions and slightly modified the documentation regarding the organism param and the example (I included the same files and organism as the other functions in the repository).
=> fix: update the docker

R/generateLibInfo.R
Adding the generateLibInfo function (htgts pipeline) after porting in R
=> feat(generateLibInfo): add generateLibInfo function
